# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f82eca7b7b64c10857f2c24d94f1b99f7ddd11583ba09227bc931c3a5b9aba3163db7f4497e7880d88f4d8c38baa56ce2f6bb6ba611d541d7514cfbfe32f97e9

test:
  secret_key_base: 84dbc26904f782fb55b3237d9a5a37c98008eb778a2ce34322ffbd4fd8ba01bc7dc1534c1c3d94d3e94392fbed7dc862441c616bd5ffd75857e2900c4d70a1fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
